version: '3'

services:
  api:
    build: .
    ports:
      - '4321:4321'
    env_file:
      - .env
    container_name: grizzly-api
    restart: on-failure
    networks:
      - grizzly

networks:
  grizzly:
